name: 'Eslint'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run eslint